# Homework 3 - Numpy

Esercizio 1: creazione array 3 x 3 con valori compresi tra 0 e 8

In [1]:
import numpy as np

In [3]:
mat_1 = np.arange(9).reshape(3,3) 
mat_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Esercizio 2: creazione vettore di 30 elementi generati casualmente ed individuazione valore medio

In [12]:
import numpy.random as rdm

v_rand = rdm.random(30)  #genesi del vettore

def mean_vector(vec):
    
    sum = 0.
    
    for x in vec:
        sum = sum + x
    
    sum = sum/vec.size
    
    print("La media degli elementi del vettore inserito è: ", sum)
    
    return sum

mean_vector(v_rand)



La media degli elementi del vettore inserito è:  0.42723552020502437


0.42723552020502437

In [13]:
np.mean(v_rand) #test

0.42723552020502437

Esercizio 3: trovare gli indici degli elementi diversi da zero del seguente array [3,5,0,4,0,8,0]

In [34]:
array_prova = np.array([3,5,0,4,0,8,0])

def trova_indici_non_zero(vec):
    
    index_list = []     #lista che conterrà gli indici richiesti
    
    j = 0               #contatore degli indici dell'array vec
    
    k = 0               #contatore degli indici della lista index_list
    
    for xx in vec:      #ciclo sugli elementi del vettore
        
        if xx != 0:
            index_list.insert(k, j) #se xx è diverso da zero inserisce nella lista l'indice corrispondente
            k += 1
        
        j += 1           #incremento dell'indice del vettore
    
    print("La lista degli indici degli elementi del vettore diversi da zero è: ", index_list)
    
    return index_list

trova_indici_non_zero(array_prova)

La lista degli indici degli elementi del vettore diversi da zero è:  [0, 1, 3, 5]


[0, 1, 3, 5]

Esercizio 4: programma per ottenere gli indici degli elementi ordinati di un dato array.

In [41]:
array_interi = rdm.randint(1, 1000, 12)
array_interi

array([ 94, 815, 532, 648, 459, 173, 639, 831, 529, 382, 359, 967])

In [45]:
def ordina_indici(vec):
    
    #genesi di un array contenente gli indici dell'array vec
    
    index_array = np.arange(vec.size)
    
    #copia degli array vec e index_array
    
    vec_cp = np.copy(vec)
    index_array_cp = np.copy(index_array)
    
    i = 0   #contatore per il ciclo while esterno
    
    a = 0
    b = 0
    c = 0
    d = 0  #variabili contenitore per lo scambio degli indici
    
    while(i < vec.size):
        
        j = 1 #contatore per il ciclo while iterno
        
        while(j < vec.size - i):
            
            if vec_cp[j - 1] > vec_cp[j]:
                
                a = vec_cp[j]
                b = vec_cp[j-1]      #scambio di posizione tra due elementi successivi dell'array
                vec_cp[j] = b        #se il minore di indice è maggiore dell'altro elemento
                vec_cp[j-1] = a
                
                
                c = index_array_cp[j]
                d = index_array_cp[j-1]      #scambio di indici corrispondente allo scambio di elementi precedente
                index_array_cp[j] = d
                index_array_cp[j-1] = c
            j += 1
            
        i += 1
        
    #stampe e confronto tra array non ordinati ed ordinati
    
    print("L'array inserito è: ", vec)
    print()
    print("L'array ordinato è: ", vec_cp)
    print()
    print("La lista degli indici è: ", index_array)
    print()
    print("La lista degli indici ordinati è: ", index_array_cp)
    
    return vec_cp, index_array_cp

ordina_indici(array_interi)
                
            

L'array inserito è:  [ 94 815 532 648 459 173 639 831 529 382 359 967]

L'array ordinato è:  [ 94 173 359 382 459 529 532 639 648 815 831 967]

La lista degli indici è:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

La lista degli indici ordinati è:  [ 0  5 10  9  4  8  2  6  3  1  7 11]


(array([ 94, 173, 359, 382, 459, 529, 532, 639, 648, 815, 831, 967]),
 array([ 0,  5, 10,  9,  4,  8,  2,  6,  3,  1,  7, 11]))

Esercizio 5: programma che calcola la media degli elementi di una matrice lungo gli assi

In [48]:
matrix_prova = 100.0*rdm.random((5,5))
matrix_prova

array([[70.97943479, 28.46409517, 63.44683856,  2.12521478, 27.99636234],
       [65.40229287, 17.22180382, 17.70033698, 42.56797185, 34.30894785],
       [87.5905551 , 27.81873903, 89.14726392, 62.00948467, 17.30574132],
       [26.06401188, 91.85779422, 71.92070232, 77.83293539, 23.57602848],
       [25.92938413, 33.22248001, 30.00333486,  8.26009478, 52.83360351]])

In [55]:
def medie_sugli_assi(mat):
    
    media_righe = [np.mean(q) for q in mat]
    
    #trasposta della matrice mat
    
    mat_t = np.transpose(mat)
    
    media_colonne = [np.mean(p) for p in mat_t]
    
    print("La matrice inserita è: ", mat)
    print()
    print("Lista delle medie delle righe: ", media_righe)
    print()
    print("Lista delle medie delle colonne: ", media_colonne)
    
    return media_righe, media_colonne

medie_sugli_assi(matrix_prova)
    
    

La matrice inserita è:  [[70.97943479 28.46409517 63.44683856  2.12521478 27.99636234]
 [65.40229287 17.22180382 17.70033698 42.56797185 34.30894785]
 [87.5905551  27.81873903 89.14726392 62.00948467 17.30574132]
 [26.06401188 91.85779422 71.92070232 77.83293539 23.57602848]
 [25.92938413 33.22248001 30.00333486  8.26009478 52.83360351]]

Lista delle medie delle righe:  [38.60238912948786, 35.440270673550415, 56.77435680742777, 58.25029445808855, 30.04977945775952]

Lista delle medie delle colonne:  [55.19313575366952, 39.716982451199, 54.44369532769027, 38.55914029394723, 31.20413669980807]


([38.60238912948786,
  35.440270673550415,
  56.77435680742777,
  58.25029445808855,
  30.04977945775952],
 [55.19313575366952,
  39.716982451199,
  54.44369532769027,
  38.55914029394723,
  31.20413669980807])